tap "buo/cask-upgrade"
tap "cloudfoundry/tap"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "sanemat/font"
tap "vitorgalvao/tiny-scripts"
brew "openssl"
brew "python"
brew "awscli"
brew "bash-completion"
brew "icu4c"
brew "boost"
brew "pcre"
brew "coreutils"
brew "diffutils"
brew "direnv"
brew "libunistring"
brew "xvid"
brew "ffmpeg"
brew "findutils", args: ["with-default-names"]
brew "mpfr"
brew "gawk"
brew "ghq"
brew "git"
brew "git-secrets"
brew "gnu-sed", args: ["with-default-names"]
brew "gnu-tar"
brew "grep", args: ["with-default-names"]
brew "gzip"
brew "htop"
brew "hub"
brew "oniguruma"
brew "jq"
brew "mackup"
brew "mas"
brew "mysql"
brew "nkf"
brew "openssl@1.1"
brew "peco"
brew "pstree"
brew "reattach-to-user-namespace"
brew "source-highlight"
brew "terraform"
brew "tig"
brew "tmux"
brew "tree"
brew "vim"
brew "wget"
brew "zsh"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "cloudfoundry/tap/cf-cli"
brew "heroku/brew/heroku"
brew "sanemat/font/ricty", args: ["with-powerline"]
brew "vitorgalvao/tiny-scripts/cask-repair"
cask "alfred"
cask "appcleaner"
cask "atom"
cask "authy"
cask "bartender"
cask "clipy"
cask "dash"
cask "discord"
cask "docker"
cask "dropbox"
cask "flux"
cask "ghost"
cask "github-desktop"
cask "google-chrome"
cask "google-japanese-ime"
cask "gyazo"
cask "intellij-idea"
cask "istat-menus"
cask "istumbler"
cask "iterm2"
cask "karabiner-elements"
cask "kitematic"
cask "qfinder-pro"
cask "shiftit"
cask "toggl"
cask "tunnelblick"
cask "typora"
cask "vagrant"
cask "virtualbox"
cask "visual-studio-code"
cask "vlc"
cask "caskroom/fonts/font-cica"
cask "caskroom/versions/java8"
cask "caskroom/versions/microsoft-remote-desktop-beta"
mas "1Password", id: 443987910
mas "Day One", id: 1055511498
mas "Evernote", id: 406056744
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "MoneyWiz", id: 465339122
mas "Night Owl", id: 428834068
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pocket", id: 568494494
mas "Quiver", id: 866773894
mas "ReceiptKeeper", id: 413449473
mas "Skitch", id: 425955336
mas "Slack", id: 803453959
mas "Spark", id: 1176895641
mas "Time Sink", id: 404363161
mas "Todoist", id: 585829637
mas "VirusScannerPlus", id: 595374522
mas "Wunderlist", id: 410628904
mas "紀伊國屋書店Kinoppy", id: 572547904
