[env]
mise.file = ".env"

[settings]
trusted_config_paths = [
  '~/src/github.com/heyinc',
]

[tools]
go = "1.26.1"
terraform = "latest"
terraform-docs = "latest"
tflint = "latest"
usage = "latest"
golangci-lint = "2.10.1"
node = "22"
ruby = "3.4.2"
gcloud = "latest"

