format = """
$all\
$fill\
$time\
$line_break\
$character
"""
command_timeout = 750

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " "
home_symbol = ""

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fill]
symbol = ' '

[gcloud]
symbol = " "

[git_branch]
symbol = " "

[git_metrics]
disabled = false

[golang]
symbol = " "

[guix_shell]
symbol = " "

[gradle]
symbol = "🐘 "

[haskell]
symbol = " "

[haxe]
symbol = "⌘ "

[hg_branch]
symbol = " "

[hostname]
ssh_only = false

[java]
symbol = " "
style = "red bold"

[julia]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = " "

[meson]
symbol = "喝 "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "﯑ "
Gentoo = " "
HardenedBSD = "ﲊ "
Illumos = " "
Linux = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = " "
openSUSE = " "
OracleLinux = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = " "
Solus = "ﴱ "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = " "

[package]
symbol = "📦 "

[python]
symbol = " "

[rlang]
symbol = "ﳒ "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[spack]
symbol = "🅢 "

[status]
disabled = false
symbol = " "
not_executable_symbol = "ﰸ "
not_found_symbol = " "
sigint_symbol = " "
signal_symbol = " "

[sudo]
disabled = false
symbol = " "

[time]
disabled = false

[username]
show_always = true
